export const courseData = [
  {
    tag: 1,
    courseIMG: "https://images-na.ssl-images-amazon.com/images/I/41MBLi5a4jL._SX384_BO1,204,203,200_.jpg",
    name: "The Road to Learn React: Your Journey to Master Plain Yet Pragmatic React.",
    author: "Robin Wieruch",
    disPrice: 535,
    orgPrice: null,
    
    desc: `The road to learn react teaches you the fundamentals of react. You will build a real world application along the way in plain react without complicated tooling. Everything from project setup to deployment on a server will be explained. The book comes with additional referenced reading material and exercises with each Chapter after reading the book, you will be able to build your own applications in react. The material is kept up to date by me and the community. In the road to learn react, I want to offer a foundation before you start to dive into the broader react ecosystem. It has less tooling and less external state management, but a lot of information around react. It explains General concepts, patterns and best practices in a real world react application. You will learn to build your own react application. It covers real world features like pagination, client-side caching and interactions like searching and sorting. Additionally you will transition from JavaScript ES5 to JavaScript ES6 along the way. I hope this book captures My enthusiasm for react and JavaScript and helps you to get started.`,
  },
  {
    tag: 2,
    courseIMG: "https://images-na.ssl-images-amazon.com/images/I/51z+MsmqesL._SX377_BO1,204,203,200_.jpg",
    name: "Core Java: An Integrated Approach, New: Includes All Versions upto Java 8a",
    author: "Nageshwara Rao",
    disPrice: 800,
    orgPrice: 956,
    desc: `Core Java ? An Integrated Approach covers all core concepts in a methodical way. It helps you learn the concepts?from OOPS to abstract classes and interfaces; from software packaging to providing API documents; from error handling to converting fundamental data into object form; from collection framework to streams and creating client and server program to threads; from creating GUI applications to generics and communication with database. This book also covers the interview questions along with the subject matter to help students do well in interviews. The questions presented in this book have been collected from various interviews.`,
  },
  {
    tag: 3,
    courseIMG: "https://images-na.ssl-images-amazon.com/images/I/41LFFu+ffJL._SX258_BO1,204,203,200_.jpg",
    name:
      "Java Script on Things: Hacking Hardware for Web Developers",
    author: "Lyza Danger Gardner ",
    disPrice: 861,
    orgPrice: null,
    desc: `This book teaches the fundamentals of electronics and embedded systems for folks who are comfortable with basic JavaScript but who may have no experience what-so-ever wiring up even the simplest circuit. Emphasis is put on the topics that will be new to software developers: the critical basics of designing and building circuits, hardware components (sensors, motors, resistors and the like) and the interface between hard-ware and software. Over the course of this book, you’ll get hands-on with a variety of development boards, hardware components and software platforms. For the experiments (small projects) in the first two-thirds of the book, we’ll use the Johnny-Five open source Node.js framework with the Arduino Uno development board. Johnny-Five’s API pro-vides many intuitive component classes that you can use to quickly prototype your gadgets and inventions.`,
  },
  {
    tag: 4,
    courseIMG: "https://images-eu.ssl-images-amazon.com/images/I/41sbWdpTgRL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
    name: "Object-Oriented Programming with C++",
    author: "E Balagurusamy",
    disPrice: 498,
    orgPrice: null,
    desc: `Object-oriented programming with C++, 8th edition is here with some valuable updates. The new edition helps students to assess their learning by answering questions based on learning outcomes. Objective-type questions and dry-run questions are introduced to make students exam ready. A new appendix on interview questions is for those seeking to join the industry. The book is designed for students studying at the undergraduate level. It provides all-inclusive concepts and programs on object-oriented programming with C++ as an implementation language. <Br> highlights:</br> 150+ multi-choice questions</br> 100+ dry-run exercises</br> 90+ interview questions</br> Two new projects</br> New appendix on implementation of abstract data types</br> classification of review questions on OBE (outcome-based education) learning pattern</br> All programs upgraded for compatibility with ansi C++`,
  },
  {
    tag: 5,
    courseIMG: "https://images-eu.ssl-images-amazon.com/images/I/41SYMXEqUKL._SX198_BO1,204,203,200_QL40_FMwebp_.jpg",
    name: "Beginning Unix (Programmer to Programmer)",
    author: "Jeremy C. Reed ",
    disPrice: 3068,
    orgPrice: null,
    desc: `Covering all aspects of the Unix operating system and assuming no prior knowledge of Unix, this book begins with the fundamentals and works from the ground up to some of the more advanced programming techniques`,
  },
  {
    tag: 6,
    courseIMG: "https://images-na.ssl-images-amazon.com/images/I/51RQd1Sh4rL._SX397_BO1,204,203,200_.jpg",
    name: "Data Mining For Dummies",
    author: "Meta S. Brown",
    disPrice: 1949,
    orgPrice: null,
    
    desc: `Data mining is quickly becoming integral to creating value and business momentum. The ability to detect unseen patterns hidden in the numbers exhaustively generated by day-to-day operations allows savvy decision-makers to exploit every tool at their disposal in the pursuit of better business. By creating models and testing whether patterns hold up, it is possible to discover new intelligence that could change your business's entire paradigm for a more successful outcome.`,
  },
  {
    tag: 7,
    courseIMG: "https://images-na.ssl-images-amazon.com/images/I/41fGgtUPnrL._SX379_BO1,204,203,200_.jpg",
    name: "Internet of Things",
    author: "Nageshwara Rao",
    disPrice: 520,
    orgPrice: 956,
    desc: `Core Java ? An Integrated Approach covers all core concepts in a methodical way. It helps you learn the concepts?from OOPS to abstract classes and interfaces; from software packaging to providing API documents; from error handling to converting fundamental data into object form; from collection framework to streams and creating client and server program to threads; from creating GUI applications to generics and communication with database. This book also covers the interview questions along with the subject matter to help students do well in interviews. The questions presented in this book have been collected from various interviews.`,
  },
  {
    tag: 8,
    courseIMG: "https://images-eu.ssl-images-amazon.com/images/I/412kMtcTHaL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
    name:
      "Hands-On System Design",
    author: "Harsh Kumar Ramchandani ",
    disPrice: 674,
    orgPrice: null,
    desc: `This book teaches the fundamentals of electronics and embedded systems for folks who are comfortable with basic JavaScript but who may have no experience what-so-ever wiring up even the simplest circuit. Emphasis is put on the topics that will be new to software developers: the critical basics of designing and building circuits, hardware components (sensors, motors, resistors and the like) and the interface between hard-ware and software. Over the course of this book, you’ll get hands-on with a variety of development boards, hardware components and software platforms. For the experiments (small projects) in the first two-thirds of the book, we’ll use the Johnny-Five open source Node.js framework with the Arduino Uno development board. Johnny-Five’s API pro-vides many intuitive component classes that you can use to quickly prototype your gadgets and inventions.`,
  },
  {
    tag: 9,
    courseIMG: "https://images-eu.ssl-images-amazon.com/images/I/41sbWdpTgRL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
    name: "Grapic Design",
    author: "M S Ramaswamy",
    disPrice: 300,
    orgPrice: null,
    desc: `Object-oriented programming with C++, 8th edition is here with some valuable updates. The new edition helps students to assess their learning by answering questions based on learning outcomes. Objective-type questions and dry-run questions are introduced to make students exam ready. A new appendix on interview questions is for those seeking to join the industry. The book is designed for students studying at the undergraduate level. It provides all-inclusive concepts and programs on object-oriented programming with C++ as an implementation language. <Br> highlights:</br> 150+ multi-choice questions</br> 100+ dry-run exercises</br> 90+ interview questions</br> Two new projects</br> New appendix on implementation of abstract data types</br> classification of review questions on OBE (outcome-based education) learning pattern</br> All programs upgraded for compatibility with ansi C++`,
  },
  {
    tag: 10,
    courseIMG: "https://images-eu.ssl-images-amazon.com/images/I/41SYMXEqUKL._SX198_BO1,204,203,200_QL40_FMwebp_.jpg",
    name: "Algorithm Design",
    author: "Rajshekhar ",
    disPrice: 3068,
    orgPrice: null,
    desc: `Covering all aspects of the Unix operating system and assuming no prior knowledge of Unix, this book begins with the fundamentals and works from the ground up to some of the more advanced programming techniques`,
  },
  {
    tag: 11,
    courseIMG: "https://images-na.ssl-images-amazon.com/images/I/41MBLi5a4jL._SX384_BO1,204,203,200_.jpg",
    name: "Operating System",
    author: "Mick Josh",
    disPrice: 788,
    orgPrice: null,
    
    desc: `The road to learn react teaches you the fundamentals of react. You will build a real world application along the way in plain react without complicated tooling. Everything from project setup to deployment on a server will be explained. The book comes with additional referenced reading material and exercises with each Chapter after reading the book, you will be able to build your own applications in react. The material is kept up to date by me and the community. In the road to learn react, I want to offer a foundation before you start to dive into the broader react ecosystem. It has less tooling and less external state management, but a lot of information around react. It explains General concepts, patterns and best practices in a real world react application. You will learn to build your own react application. It covers real world features like pagination, client-side caching and interactions like searching and sorting. Additionally you will transition from JavaScript ES5 to JavaScript ES6 along the way. I hope this book captures My enthusiasm for react and JavaScript and helps you to get started.`,
  },
  {
    tag: 12,
    courseIMG: "https://images-na.ssl-images-amazon.com/images/I/51z+MsmqesL._SX377_BO1,204,203,200_.jpg",
    name: "Python",
    author: "Nageshwara",
    disPrice: 800,
    orgPrice: 956,
    desc: `Core Java ? An Integrated Approach covers all core concepts in a methodical way. It helps you learn the concepts?from OOPS to abstract classes and interfaces; from software packaging to providing API documents; from error handling to converting fundamental data into object form; from collection framework to streams and creating client and server program to threads; from creating GUI applications to generics and communication with database. This book also covers the interview questions along with the subject matter to help students do well in interviews. The questions presented in this book have been collected from various interviews.`,
  },
];
